### ISSUE TITLE
Infinite spinner when using ListWidget

### ISSUE THREAD

**Issue by mark-yacoub** [sAleksovski/react-native-android-widget#17]
thanks a lot for the widget, it's been working great.
I tried upgrading to use ListView but it has a problem:

here is my code
```
    <FlexWidget style={styles.container}>
      {renderDate()}
      {/* There is bug in using array.map so just render as many as we can. */}

      <ListWidget>
        {renderTask(0)}
        {/*     {renderTask(1)}
        {renderTask(2)}
        {renderTask(3)}
        {renderTask(4)}
        {renderTask(5)}
        {renderTask(6)} */}
      </ListWidget>
    </FlexWidget>
```

   with this code, im getting an infinite spinner when i'm previewing it in my app 
<img width="186" alt="image" src="https://github.com/sAleksovski/react-native-android-widget/assets/11547193/2e67a30c-8910-43df-8cb7-0f62b50d4d52">
and the widget on the home screen isn't loading 
<img width="343" alt="image" src="https://github.com/sAleksovski/react-native-android-widget/assets/11547193/d1ae53f0-76e2-47bf-915c-d68a4cc956f3">

thanks!

**Comment by sAleksovski** [comment]
Hi.

What error are you getting in the console?
Can you share the complete code of the widget, or create a minimal widget that reproduces the issue so I can test it?

There was an issue when using a widget next to `array.map`, but it should be fixed id `0.5.1`.

**Comment by mark-yacoub** [comment]
for sure, i was able to repro down to this
```
const CanonTrackerWidget = () => {
  const myTasks = [{name: 'hi'}, {name: 'bye'}];

  return (
    <FlexWidget>
      <ListWidget>
        {myTasks.map(task => (
          <TextWidget key={task.name}>{task.name}</TextWidget>
        ))}
      </ListWidget>
    </FlexWidget>
  );
};
  ```

**Comment by sAleksovski** [comment]
TextWidget accepts a `text` prop for the text, the text should not be inside the TextWidget.

https://saleksovski.github.io/react-native-android-widget/docs/public-api/interfaces/TextWidgetProps

**Comment by mark-yacoub** [comment]
hey - sorry for the mistake, i was trying to create a small example to repro.
the issue isn't yet solved even after fixing the text.
Thanks for the followup!

**Comment by sAleksovski** [comment]
Can you share the error you are getting?

Another thing I can think of is not setting the size (height/width) for the `ListWidget`, but I'm not sure if that's the case for your widget that's not present in the small example.

**Comment by mark-yacoub** [comment]
I modified my small example to include the h and w
```
const CanonTrackerWidget = () => {
  const myTasks = [{name: 'hi'}, {name: 'bye'}];

  return (
    <FlexWidget>
      <ListWidget
        style={{
          height: 'match_parent',
          width: 'match_parent',
          backgroundColor: '#1F3529',
        }}>
        {myTasks.map(task => (
          <TextWidget key={task.name}>{task.name}</TextWidget>
        ))}
      </ListWidget>
    </FlexWidget>
  );
};
```
also attempted to change height and width to 300.
so here is what is happening:
I see no error or warning in the logs, everything seems fine.
I see the same spinner as the screenshot above in the preview in my RN app, and the same gray "click to update widget" on the main screen.

**Comment by sAleksovski** [comment]
I just released `0.5.2` version of the library.

I think that the problem was that you didn't have `clickAction` and `clickActionData` on the items inside `ListWidget`.
I fixed that bug, and it should work correctly now.

Another issue with the example (besides the `{task.name}` inside `TextWidget` which should be set as a `text` prop) is that the `ListWidget` has a height/width of 0. I think you don't have that issue in your real widget.

Please try the new version, and see if it fixes your issue.

**Comment by mark-yacoub** [comment]
Okay I figure out what's going on. I copied your ListWidget example and starting modifying closer to my sample code. It turns out, it's the FlexWidget around the ListView.

I think I need it because i need a header to the list, then i want the user to scroll the list while the header is there.

Here is a repro code
```
const CanonTrackerWidget = () => {
  return (
    <FlexWidget>
      <ListWidget
        style={{
          height: 'match_parent',
          width: 'match_parent',
          backgroundColor: '#1F3529',
          flex: 1,
        }}>
        {Array.from({length: 15}).map((_, i) => (
          <FlexWidget
            key={i}
            style={{
              width: 'match_parent',
              alignItems: 'center',
              flexDirection: 'row',
              justifyContent: 'center',
              padding: 8,
            }}
            clickAction='OPEN_URI'
            clickActionData={{
              uri: `androidwidgetexample://list/list-demo/${i + 1}`,
            }}>
            <TextWidget text={`React Native Android Widget Release 0.${i + 1}`} />
          </FlexWidget>
        ))}
      </ListWidget>
    </FlexWidget>
  );
};
```

**Comment by sAleksovski** [comment]
The problem with the latest code you shared is that the first `FlexWidget` does not have size.

It's default size is `match_content` (meaning it's size is the same as the size of it's children).
But `ListWidget` has a `match_parent` height/width, meaning `0`.

You should put `style={{ height: 'match_parent', width: 'match_parent' }}` on the first `FlexWidget`.

Also, `ListWidget` does not accept `flex: 1` style prop.

I released a new version, `0.5.3` that will log the native error so it can be easier to see what the error is.

Can you confirm it works now?

**Comment by mark-yacoub** [comment]
I have a feeling this might have broke the widget. like it works fine within the react native preview but not when it's on the home screen. I'll double check tomorrow though i might be wrong

**Comment by mark-yacoub** [comment]
Something is a bit weird.
Here is what it looks like when previewd inside my app:
<img width="376" alt="image" src="https://github.com/sAleksovski/react-native-android-widget/assets/11547193/fcf926f7-989a-4813-ba18-638b7e6bbd9c">
but here is what it looks like on the home screen
<img width="317" alt="image" src="https://github.com/sAleksovski/react-native-android-widget/assets/11547193/a1cd5fe7-6a2b-4f6c-8320-0745419ad518">
this is my code
```
export function CanonTrackerWidget() {
  return (
    <ListWidget
      style={{
        height: 'match_parent',
        width: 'match_parent',
        backgroundColor: '#1F3529',
      }}>
      {Array.from({length: 15}).map((_, i) => (
        <FlexWidget
          key={i}
          style={{
            width: 'match_parent',
            alignItems: 'center',
            flexDirection: 'row',
            justifyContent: 'center',
            padding: 8,
          }}
          clickAction='OPEN_URI'
          clickActionData={{
            uri: `androidwidgetexample://list/list-demo/${i + 1}`,
          }}>
          <TextWidget text={`React Native Android Widget Release 0.${i + 1}`} />
        </FlexWidget>
      ))}
    </ListWidget>
  );
}
```

**Comment by sAleksovski** [comment]
@mark-yacoub Any update here? Did you make it work?

**Comment by mark-yacoub** [comment]
So I tried it on a physical device and things aren't great.
without the listwidget, things are in good order as shown in the following screenshot 
![image](https://github.com/sAleksovski/react-native-android-widget/assets/11547193/5f465f2c-d89d-4147-9a1a-4e37cbcf62de)

however, you can see that the widget is always not reaching the edge of the widget border.
Here is my xml
```
<?xml version="1.0" encoding="utf-8"?>
<!-- https://saleksovski.github.io/react-native-android-widget/docs/tutorial/register-widget#add-a-widget-provider-xml-file -->
<appwidget-provider xmlns:android="http://schemas.android.com/apk/res/android"
    android:targetCellWidth="3"
    android:targetCellHeight="2"

    android:updatePeriodMillis="1860000"

    android:initialLayout="@layout/rn_widget"

    android:previewImage="@drawable/widget_screenshot"
    android:description="@string/widget_description"

    android:resizeMode="horizontal|vertical"

    android:widgetCategory="home_screen">
</appwidget-provider>
```

here is my container
```
  return (
    <FlexWidget style={styles.container}>
      {renderDate()}
      {!!tasksForDate.length && renderTasks()}
      {!tasksForDate.length && renderNoTasks()}
    </FlexWidget>
  );
};

const styles = {
  container: {
    backgroundColor: '#ffffff',
    borderRadius: 16,
    flex: 1,
    height: '130',
    overflow: 'auto',
    paddingVertical: 5,
    width: 'match_parent',
  },
```

currently, this is my renderTasks
```
  const renderTasks = () => tasksForDate.map(task => renderTask(task));
```
however, once i wrap in List widget like
```
  const renderTasks = () => (
    <ListWidget style={{height: 'match_parent', width: 'match_parent'}}>
      {tasksForDate.map(task => renderTask(task))}
    </ListWidget>
  );
```
it starts acting weird and it looks like
![image](https://github.com/sAleksovski/react-native-android-widget/assets/11547193/fb3e1604-a769-4764-9518-fc55052cf65a)

scrolling is great though.
